[package]
name = "rev_shell_client"
version = "0.1.0"
edition = "2021"
authors = ["nthdeg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
